In [3]:
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as svm
%matplotlib inline
import pandas as pd
import csv
import numpy as np
from sklearn import preprocessing
import statistics
import sys

In [4]:
ds_collab = pd.read_csv('steam-200k.csv')

In [5]:
ds_collab.head(20)

      user_id                        name    status  hours
0   151603712  The Elder Scrolls V Skyrim  purchase    1.0
1   151603712  The Elder Scrolls V Skyrim      play  273.0
2   151603712                   Fallout 4  purchase    1.0
3   151603712                   Fallout 4      play   87.0
4   151603712                       Spore  purchase    1.0
5   151603712                       Spore      play   14.9
6   151603712           Fallout New Vegas  purchase    1.0
7   151603712           Fallout New Vegas      play   12.1
8   151603712               Left 4 Dead 2  purchase    1.0
9   151603712               Left 4 Dead 2      play    8.9
10  151603712                    HuniePop  purchase    1.0
11  151603712                    HuniePop      play    8.5
12  151603712               Path of Exile  purchase    1.0
13  151603712               Path of Exile      play    8.1
14  151603712                 Poly Bridge  purchase    1.0
15  151603712                 Poly Bridge      play    7.5
16  151603712                 Left 4 Dead  purchase    1.0
17  151603712                 Left 4 Dead      play    3.3
18  151603712             Team Fortress 2  purchase    1.0
19  151603712             Team Fortress 2      play    2.8

In [6]:
ds_collab.size

800000

In [7]:
#Preprocessing

In [8]:
ds_collab = ds_collab[ds_collab['status'] == 'play'].copy()

In [9]:
ds_collab.head(20)

      user_id                                   name status  hours
1   151603712             The Elder Scrolls V Skyrim   play  273.0
3   151603712                              Fallout 4   play   87.0
5   151603712                                  Spore   play   14.9
7   151603712                      Fallout New Vegas   play   12.1
9   151603712                          Left 4 Dead 2   play    8.9
11  151603712                               HuniePop   play    8.5
13  151603712                          Path of Exile   play    8.1
15  151603712                            Poly Bridge   play    7.5
17  151603712                            Left 4 Dead   play    3.3
19  151603712                        Team Fortress 2   play    2.8
21  151603712                            Tomb Raider   play    2.5
23  151603712                        The Banner Saga   play    2.0
25  151603712                   Dead Island Epidemic   play    1.4
27  151603712                      BioShock Infinite   play    1.3
29  151603712  Dragon Age Origins - Ultimate Edition   play    1.3
31  151603712   Fallout 3 - Game of the Year Edition   play    0.8
33  151603712     SEGA Genesis & Mega Drive Classics   play    0.8
35  151603712                    Grand Theft Auto IV   play    0.6
37  151603712                   Realm of the Mad God   play    0.5
39  151603712                     Marvel Heroes 2015   play    0.5

In [10]:
hours_played_each_game = pd.DataFrame(index=ds_collab['user_id'].unique(), columns=ds_collab['name'].unique())

In [11]:
hours_played_each_game

,The Elder Scrolls V Skyrim,Fallout 4,Spore,Fallout New Vegas,Left 4 Dead 2,HuniePop,Path of Exile,Poly Bridge,Left 4 Dead,Team Fortress 2,...,Adventure Time Explore the Dungeon Because I DONT KNOW!,Ride! Carnival Tycoon,SAMURAI WARRIORS 4-II,The Bug Butcher,Romance of the Three Kingdoms Maker,Space Colony,Life is Hard,Executive Assault,O.R.B.,MirrorMoon EP
151603712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187131847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59945701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53875128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140954425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125424716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99096740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176449171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221315846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128470551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
hours_played_each_game['The Elder Scrolls V Skyrim']

151603712    NaN
187131847    NaN
59945701     NaN
53875128     NaN
140954425    NaN
            ...
125424716    NaN
99096740     NaN
176449171    NaN
221315846    NaN
128470551    NaN
Name: The Elder Scrolls V Skyrim, Length: 11350, dtype: object

In [13]:
for i in range(len(ds_collab)):
  user_id = ds_collab.iloc[i]['user_id']
  name = ds_collab.iloc[i]['name']
  hours_played_each_game.loc[user_id,name] = ds_collab.iloc[i]['hours']

In [14]:
hours_played_each_game

,The Elder Scrolls V Skyrim,Fallout 4,Spore,Fallout New Vegas,Left 4 Dead 2,HuniePop,Path of Exile,Poly Bridge,Left 4 Dead,Team Fortress 2,...,Adventure Time Explore the Dungeon Because I DONT KNOW!,Ride! Carnival Tycoon,SAMURAI WARRIORS 4-II,The Bug Butcher,Romance of the Three Kingdoms Maker,Space Colony,Life is Hard,Executive Assault,O.R.B.,MirrorMoon EP
151603712,273.0,87.0,14.9,12.1,8.9,8.5,8.1,7.5,3.3,2.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187131847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59945701,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53875128,NaN,NaN,0.5,7.5,71.0,NaN,NaN,NaN,1.7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140954425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125424716,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,59.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99096740,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176449171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221315846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128470551,NaN,NaN,NaN,NaN,NaN,NaN,42.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
hours_played_each_game.to_csv('each_game_playtime.csv', index=True)

In [16]:
each_item = pd.read_csv('each_game_playtime.csv')

In [17]:
each_item.head()

,Unnamed: 0,The Elder Scrolls V Skyrim,Fallout 4,Spore,Fallout New Vegas,Left 4 Dead 2,HuniePop,Path of Exile,Poly Bridge,Left 4 Dead,...,Adventure Time Explore the Dungeon Because I DONT KNOW!,Ride! Carnival Tycoon,SAMURAI WARRIORS 4-II,The Bug Butcher,Romance of the Three Kingdoms Maker,Space Colony,Life is Hard,Executive Assault,O.R.B.,MirrorMoon EP
0,151603712,273.0,87.0,14.9,12.1,8.9,8.5,8.1,7.5,3.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,187131847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,59945701,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,53875128,NaN,NaN,0.5,7.5,71.0,NaN,NaN,NaN,1.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,140954425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
each_item_norm = np.log(each_item)
each_item_norm += abs(each_item_norm.min().min())
print(each_item_norm.min().min(), each_item_norm.max().max())
each_item_norm = each_item_norm[(~each_item_norm.isnull()).sum(axis=1) >= 3]
each_item_norm

NameError: name 'np' is not defined

In [1]:
each_item_norm

NameError: name 'each_item_norm' is not defined